interfaces:
  GigabitEthernet 1/1:
    state: "down"
  GigabitEthernet 1/2:
    state: "down"
  GigabitEthernet 1/3:
    state: "down"
  GigabitEthernet 1/4:
    state: "down"
  GigabitEthernet 1/5:
    state: "down"
  GigabitEthernet 1/6:
    state: "down"
  GigabitEthernet 1/7:
    state: "down"
  GigabitEthernet 1/8:
    state: "down"
  GigabitEthernet 1/9:
    state: "down"
  GigabitEthernet 1/10:
    state: "down"
  GigabitEthernet 1/11:
    state: "down"
  GigabitEthernet 1/12:
    state: "down"
  GigabitEthernet 1/13:
    state: "down"
  GigabitEthernet 1/14:
    state: "down"
  GigabitEthernet 1/15:
    state: "down"
  GigabitEthernet 1/16:
    state: "down"
  GigabitEthernet 1/17:
    state: "down"
  GigabitEthernet 1/18:
    state: "down"
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    description: "OCT-HEAD"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
      - 910
      - 915
      - 931
      - 933
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    state: "down"
  GigabitEthernet 1/34:
    state: "down"
  GigabitEthernet 1/35:
    state: "down"
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    description: "OCT-MCORE-2 Link"
    state: "up"
    portmode: "access"
    tagged: "all"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    state: "down"
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    description: "OCT-CORE-1 Port 5/1"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/52:
    description: "OCT-CORE-2 Port 5/1"
    state: "up"
    mtu: 9216
  Port-channel 10:
    description: "OCT-CORE-1 and OCT-CORE-2 LAG"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Vlan 931:
    state: "up"
    ip4: "10.81.1.11/20"
