interfaces:
  GigabitEthernet 1/1:
    state: "up"
    portmode: "access"
    untagged: 930
  GigabitEthernet 1/2:
    state: "up"
    portmode: "access"
    untagged: 930
  GigabitEthernet 1/3:
    state: "down"
  GigabitEthernet 1/4:
    state: "down"
  GigabitEthernet 1/5:
    state: "down"
  GigabitEthernet 1/6:
    state: "down"
  GigabitEthernet 1/7:
    state: "down"
  GigabitEthernet 1/8:
    state: "down"
  GigabitEthernet 1/9:
    state: "down"
  GigabitEthernet 1/10:
    state: "down"
  GigabitEthernet 1/11:
    state: "down"
  GigabitEthernet 1/12:
    state: "down"
  GigabitEthernet 1/13:
    state: "down"
  GigabitEthernet 1/14:
    state: "down"
  GigabitEthernet 1/15:
    state: "down"
  GigabitEthernet 1/16:
    state: "down"
  GigabitEthernet 1/17:
    description: "oct-head"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged:
      - 930
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/18:
    state: "down"
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    state: "down"
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    description: "OCT10-00 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/34:
    description: "OCT10-01 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/35:
    description: "OCT10-02 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/36:
    description: "OCT10-03 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/37:
    description: "OCT10-04 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/38:
    description: "OCT10-05 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/39:
    description: "OCT10-06 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    state: "down"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    description: "ESI Undercloud Port 1"
    state: "up"
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 911
      - 912
    stp:
      edgeport: true
      bpduguard: true
  GigabitEthernet 1/48:
    description: "ESI Undercloud Port 2"
    state: "up"
    portmode: "access"
    untagged: 214
    stp:
      edgeport: true
      bpduguard: true
  TenGigabitEthernet 1/49:
    description: "MOC-CORE-1 Port 33"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/50:
    description: "MOC-CORE-2 Port 33"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/51:
    description: "MOC-MCORE-2 Port 51"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/52:
    description: "MOC-MCORE-2 Port 52"
    state: "up"
    mtu: 9216
  Port-channel 10:
    description: "MOC-MCORE-2 LAG"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Port-channel 101:
    description: "MOC-CORE Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/49"
      - "TenGigabitEthernet 1/50"
  Vlan 930:
    state: "up"
    ip4: "10.80.1.11/20"
