interfaces:
  twentyFiveGigE 1/1:
    state: "up"
    portmode: access
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/2:
    state: "up"
    portmode: trunk
    tagged:
      - 201
      - 250
      - 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/3:
    state: "up"
    portmode: access
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/4:
    state: "up"
    portmode: trunk
    tagged:
      - 201
      - 250
      - 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/5:
    state: "up"
    portmode: access
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/6:
    state: "up"
    portmode: trunk
    tagged:
      - 201
      - 250
      - 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/7:
    state: "up"
    portmode: access
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/8:
    state: "up"
    portmode: trunk
    tagged:
      - 201
      - 250
      - 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/9:
    state: "up"
    portmode: access
    untagged: 249
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/10:
    state: "up"
    portmode: trunk
    tagged:
      - 201
      - 250
      - 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/11:
    state: "up"
    portmode: access
    untagged: 250
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/12:
    state: "up"
    portmode: access
    untagged: 277
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/13:
    state: "down"
  twentyFiveGigE 1/14:
    state: "down"
  twentyFiveGigE 1/15:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/16:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/17:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/18:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/19:
    state: "down"
  twentyFiveGigE 1/20:
    state: "down"
  twentyFiveGigE 1/21:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/22:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/23:
    state: "down"
  twentyFiveGigE 1/24:
    state: "down"
  twentyFiveGigE 1/25:
    state: "down"
  twentyFiveGigE 1/26:
    state: "up"
    portmode: "trunk"
    tagged: "all"
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/27:
    state: "up"
    portmode: "access"
    untagged: 204
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/28:
    state: "up"
  twentyFiveGigE 1/29:
    state: "up"
    portmode: "access"
    untagged: 204
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/30:
    state: "up"
  twentyFiveGigE 1/31:
    state: "up"
    portmode: "access"
    untagged: 204
    stp:
      edgeport: true
      bpduguard: true
  twentyFiveGigE 1/32:
    state: "up"
  twentyFiveGigE 1/33:
    state: "down"
  twentyFiveGigE 1/34:
    state: "down"
  twentyFiveGigE 1/35:
    state: "down"
  twentyFiveGigE 1/36:
    state: "down"
  twentyFiveGigE 1/37:
    state: "down"
  twentyFiveGigE 1/38:
    state: "down"
  twentyFiveGigE 1/39:
    state: "down"
  twentyFiveGigE 1/40:
    state: "down"
  twentyFiveGigE 1/41:
    state: "down"
  twentyFiveGigE 1/42:
    state: "down"
  twentyFiveGigE 1/43:
    state: "down"
  twentyFiveGigE 1/44:
    state: "down"
  twentyFiveGigE 1/45:
    description: "port-channel to SFCORE-MGH-MDA-R6C23-1 eth2/5"
    state: "up"
    portmode: "trunk"
    tagged:
      - 150
      - 3800
      - 3802
    stp:
      disabled: true
  twentyFiveGigE 1/46:
    state: "down"
  twentyFiveGigE 1/47:
    description: "MOC-R4PAC02-SW-MGMT Port 51"
    state: "up"
    mtu: 9216
  twentyFiveGigE 1/48:
    description: "MOC-R4PAC02-SW-MGMT Port 52"
    state: "up"
    mtu: 9216
  hundredGigE 1/49:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/49/1:
    description: "NFS/DRBD server"
    state: "up"
    portmode: "trunk"
    tagged: "all"
  hundredGigE 1/50:
    state: "down"
  hundredGigE 1/51:
    state: "down"
  hundredGigE 1/52:
    state: "down"
  hundredGigE 1/53:
    description: "MOC-CORE-3 Uplink"
    state: "up"
    mtu: 9216
  hundredGigE 1/54:
    description: "MOC-CORE-4 Uplink"
    state: "up"
    mtu: 9216
  Port-channel 10:
    description: "MOC-CORE LAG"
    state: "up"
    tagged: "all"
    portmode: "trunk"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/53"
      - "hundredGigE 1/54"
  Port-channel 101:
    description: "MOC-R4PAC02-SW-MGMT Uplink"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "twentyFiveGigE 1/47"
      - "twentyFiveGigE 1/48"
    mlag: "Port-channel 101"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.81/20"
