interfaces:
  hundredGigE 1/1:
    description: "OCT-CORE-1 Port 28 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/2:
    description: "OCT-CORE-2 Port 28 Po10"
    state: "up"
    mtu: 9216
  hundredGigE 1/3:
    state: "down"
  hundredGigE 1/4:
    state: "down"
  hundredGigE 1/5:
    state: "down"
  hundredGigE 1/6:
    state: "down"
  hundredGigE 1/7:
    state: "down"
  hundredGigE 1/8:
    state: "down"
  hundredGigE 1/9:
    state: "down"
  hundredGigE 1/10:
    state: "down"
  hundredGigE 1/11:
    state: "down"
  hundredGigE 1/12:
    state: "down"
  hundredGigE 1/13:
    state: "down"
  hundredGigE 1/14:
    state: "down"
  hundredGigE 1/15:
    state: "down"
  hundredGigE 1/16:
    state: "down"
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    state: "down"
  hundredGigE 1/22:
    state: "down"
  hundredGigE 1/23:
    state: "down"
  hundredGigE 1/24:
    state: "down"
  hundredGigE 1/25:
    state: "down"
  hundredGigE 1/26:
    state: "down"
  hundredGigE 1/27:
    description: "OCT-CORE-3 Port 27 VLT"
    state: "up"
  hundredGigE 1/28:
    description: "OCT-CORE-3 Port 28 VLT"
    state: "up"
  hundredGigE 1/29:
    state: "down"
  hundredGigE 1/30:
    state: "down"
  hundredGigE 1/31:
    state: "down"
  hundredGigE 1/32:
    state: "down"
  TenGigabitEthernet 1/33:
    description: "OCT-MCORE-2 Port 52 Po300"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/34:
    state: "down"
  Port-channel 10:
    description: "OCT-CORE-1 and OCT-CORE-2 Core LAG"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/1"
      - "hundredGigE 1/2"
    mlag: "Port-channel 10"
  Port-channel 100:
    description: "OCT-CORE-3 VLT LAG"
    state: "up"
    mtu: 9216
    lag-members:
      - "hundredGigE 1/27"
      - "hundredGigE 1/28"
  Port-channel 300:
    description: "OCT-MCORE-2 LAG"
    state: "up"
    portmode: "trunk"
    tagged: "all"
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/33"
    mlag: "Port-channel 300"
    stp:
      rootguard: true
  Vlan 931:
    state: "up"
    ip4: "10.81.1.4/20"
